// functions/src/scripts/recompressReceipts.ts
//
// One-off backfill job.
//
// PR #211 added client-side compression so new receipts are resized to a max of
// 1600px and re-encoded as JPEG at 80% quality before they are uploaded
// (see src/firebase/storageService.ts). Receipts uploaded before that change are
// still stored at their original, full size.
//
// This script walks every receipt original in Cloud Storage and applies the same
// optimisation to bring legacy files in line. Each image is re-encoded *in place*
// so the storage path is unchanged, and the existing Firebase download token is
// preserved, which means fuelLogs.receiptUrl values keep resolving without any
// Firestore update. Overwriting the original re-triggers processReceipt, so
// thumbnails are regenerated automatically.
//
// Usage (from the functions/ directory):
//   npm run recompress-receipts            # re-compress in place
//   npm run recompress-receipts -- --dry-run   # report savings, write nothing
//
// Credentials are read via application default credentials, e.g.:
//   GOOGLE_APPLICATION_CREDENTIALS=../service-account.json npm run recompress-receipts

import { initializeApp, getApps, applicationDefault } from 'firebase-admin/app';
import { getStorage } from 'firebase-admin/storage';
import sharp from 'sharp';

const BUCKET = process.env.STORAGE_BUCKET ?? 'fuelog-paddez.firebasestorage.app';
const RECEIPTS_PREFIX = 'receipts/';
const THUMB_PREFIX = 'thumb_';

// Mirror the client-side upload compression in src/firebase/storageService.ts.
const MAX_DIMENSION = 1600;
const JPEG_QUALITY = 80;

const DRY_RUN = process.argv.includes('--dry-run');

function formatBytes(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

async function main(): Promise<void> {
    if (getApps().length === 0) {
        initializeApp({ credential: applicationDefault(), storageBucket: BUCKET });
    }
    const bucket = getStorage().bucket(BUCKET);

    console.log(`Scanning gs://${BUCKET}/${RECEIPTS_PREFIX} ...`);
    console.log(
        `Target: max ${MAX_DIMENSION}px, JPEG quality ${JPEG_QUALITY}%` +
        (DRY_RUN ? '  (dry run — nothing will be written)' : ''),
    );

    // Stream the listing rather than buffering every File object in memory, so the
    // job scales to buckets with a large number of receipts without risking OOM.
    const filesStream = bucket.getFilesStream({ prefix: RECEIPTS_PREFIX });

    let processed = 0;
    let skipped = 0;
    let failed = 0;
    let bytesBefore = 0;
    let bytesAfter = 0;

    for await (const file of filesStream) {
        const name = file.name;
        const base = name.substring(name.lastIndexOf('/') + 1);

        // Skip "folder" placeholders and thumbnails. Thumbnails are already small
        // and are regenerated by processReceipt when the original is overwritten.
        if (name.endsWith('/')) continue;
        if (base.startsWith(THUMB_PREFIX)) { skipped++; continue; }

        try {
            // The listing already populated file.metadata, so reuse it instead of
            // issuing a redundant getMetadata() request per file.
            const meta = file.metadata;
            const contentType = meta.contentType ?? '';
            if (!contentType.startsWith('image/')) { skipped++; continue; }

            // Only rewrite files that already carry a Firebase download token —
            // overwriting without preserving it would invalidate receiptUrl.
            const existingToken = meta.metadata?.firebaseStorageDownloadTokens;
            if (!existingToken) {
                console.warn(`  skip  ${name}  (no download token; leaving untouched)`);
                skipped++;
                continue;
            }

            const originalSize = Number(meta.size ?? 0);
            const [buffer] = await file.download();

            const recompressed = await sharp(buffer)
                .rotate() // honour EXIF orientation before metadata is stripped
                .resize({
                    width: MAX_DIMENSION,
                    height: MAX_DIMENSION,
                    fit: 'inside',
                    withoutEnlargement: true,
                })
                .jpeg({ quality: JPEG_QUALITY })
                .toBuffer();

            // Keep the job idempotent: skip anything that would not get smaller
            // (e.g. images the client already compressed on a recent upload).
            if (recompressed.length >= originalSize) {
                skipped++;
                continue;
            }

            bytesBefore += originalSize;
            bytesAfter += recompressed.length;
            processed++;

            const saved = originalSize - recompressed.length;
            console.log(
                `  ${DRY_RUN ? 'would shrink' : 'shrink'}  ${name}  ` +
                `${formatBytes(originalSize)} -> ${formatBytes(recompressed.length)}  (-${formatBytes(saved)})`,
            );

            if (DRY_RUN) continue;

            await file.save(recompressed, {
                resumable: false,
                metadata: {
                    contentType: 'image/jpeg',
                    // Retains firebaseStorageDownloadTokens so the public URL stays valid.
                    metadata: meta.metadata,
                },
            });
        } catch (err) {
            failed++;
            console.error(`  fail  ${name}: ${(err as Error).message}`);
        }
    }

    const saved = bytesBefore - bytesAfter;
    const pct = bytesBefore > 0 ? ((saved / bytesBefore) * 100).toFixed(1) : '0';

    console.log('\nDone.');
    console.log(`  ${DRY_RUN ? 'Would re-compress' : 'Re-compressed'}: ${processed}`);
    console.log(`  Skipped:        ${skipped}`);
    console.log(`  Failed:         ${failed}`);
    if (processed > 0) {
        console.log(
            `  Size: ${formatBytes(bytesBefore)} -> ${formatBytes(bytesAfter)}  ` +
            `(saved ${formatBytes(saved)}, ${pct}%)`,
        );
    }
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
